- name: create folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://34.204.76.187:8080
    user: admin
    password: "{{jenkins_password}}"
    environment:
      PYTHONPATH: "/usr/lib/python3.6/site-packages"
  loop:
    - CIPipelines

- name: create pipeline jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop:
  - "{{pipelinejobs}}"
