- name: add python-jenkins library to sys.path
  command: python -c "import sys; sys.path.append('/usr/local/lib/python3.9')"

- name: create folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://34.204.76.187:8080
    user: admin
    password: "{{jenkins_password}}"
  loop:
  - CIPipelines

- name: create pipeline jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop:
  - "{{pipelinejobs}}"
