- name: create config files
  ansible.builtin.template:
     src: s-job.xml
     dest: /tmp/s-job.xml

- name: Create job
  community.general.jenkins_job:
   config: "{{ lookup('template', '/tmp/s-job.xml') }}"
   name: "{{item.dir}}/{{item.name}}"
   url: http://100.26.229.148:8080/
   user: admin
   password: "{{jenkins_password}}"

