 community.general.jenkins_job:
   config: "{{ lookup('template', 'template/job.xml) }}"
   name: "{{item.dir}}/{{item.name}}"
   url: "{{jenkins_url}}"
   user: admin
   password: "{{jenkins_password}}"