- name: create config files
  ansible.builtin.template:
     src: s-job.xml
     dest: /tmp/s-job.xml

- name: Create job
  community.general.jenkins_job:
   config: "{{ lookup('file', 'temp/s-job.xml) }}"
   name: "{{item.dir}}/{{item.name}}"
   url: http://34.204.76.187:8080
   user: admin
   password: "{{jenkins_password}}"