- name: create config files
  ansible.builtin.template:
     src: job.xml
     dest: /tmp/job.xml

- name: Create job
  community.general.jenkins_job:
   config: "{{ lookup('template', 'template/job.xml) }}"
   name: "{{item.dir}}/{{item.name}}"
   url: http://34.204.76.187:8080
   user: admin
   password: "{{jenkins_password}}"