- name: create config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml

- name: create
  community.general.jenkins_job:
    config: "{{ lookup('file'), '/tmp/s-job.xml') }}"
    name: "{{item}}"
    url: http://54.236.51.144:8080
    user: admin
    password: "{{jenkins_password}}"